from enum import Enum

class EntityResolution(Enum):
    PERSON = "PERSON"
    ORG = "ORGANIZATION"
    
    PRIMARY = 'PRIMARY'
    AKA = 'ALIAS'
    
    NAME_FULL = 'NAME_FULL'
    NAME_ORG = 'NAME_ORG'
    NAME_LAST = 'NAME_LAST'
    NAME_FIRST = 'NAME_FIRST'
    NAME_MIDDLE = 'NAME_MIDDLE'
    NAME_PREFIX = 'NAME_PREFIX'
    NAME_SUFFIX = 'NAME_SUFFIX'

    ALIAS = "HAS_ALIAS"
    NO_ALIAS = "NO_ALIAS"

    ADDR_FULL = 'ADDR_FULL'
    ADDR_LINE1 = 'ADDR_LINE1'
    ADDR_LINE2 = 'ADDR_LINE2'
    ADDR_LINE3 = 'ADDR_LINE3'
    ADDR_LINE4 = 'ADDR_LINE4'
    ADDR_LINE5 = 'ADDR_LINE5'
    ADDR_LINE6 = 'ADDR_LINE6'
    ADDR_CITY = 'ADDR_CITY'
    ADDR_STATE = 'ADDR_STATE'
    ADDR_ZIP = 'ADDR_POSTAL_CODE'
    ADDR_COUNTRY = 'ADDR_COUNTRY'
    ADDR_FD = 'ADDR_FROM_DATE'
    ADDR_TD = 'ADDR_THRU_DATE'

    ALT_ADDR = 'ALTERNATE_ADDRESS'
    NO_ALT_ADDR = 'NO_ALTERNATE_ADDRESS'

    HOME = "HOME"
    MAILING = "MAILING"
    BUSINESS = "BUSINESS"
    MOBILE = 'MOBILE'
    OTHER = "OTHER"

    PHONE_NUM = 'PHONE_NUMBER'
    PHONE_FD = 'PHONE_FROM_DATE'
    PHONE_TD = 'PHONE_THRU_DATE'

    ALT_PHONE = 'ALTERNATE_PHONE'
    NO_ALT_PHONE = 'NO_ALTERNATE_PHONE'

    PASSPORT = 'PASSPORT_NUMBER'
    PASSPORT_COUNTRY = 'PASSPORT_COUNTRY'
    DRIVERS_LICENSE = 'DRIVERS_LICENSE_NUMBER'
    DRIVERS_LICENSE_STATE = 'DRIVERS_LICENSE_STATE'
    SSN = "SSN_NUMBER"
    SSN_LAST4 = "SSN_LAST4"
    NIN = 'NATIONAL_ID_NUMBER'
    NIN_COUNTRY = "NATIONAL_ID_NUMBER_COUNTRY"
    TAX_ID_TYPE = 'TAX_ID_TYPE'
    TAX_ID = "TAX_ID_NUMBER"
    TAX_ID_COUNTRY = 'TAX_ID_COUNTRY'
    OTHER_ID_TYPE = 'OTHER_ID_TYPE'
    OTHER_ID = 'OTHER_ID_NUMBER'
    OTHER_ID_COUNTRY = 'OTHER_ID_COUNTRY'
    TRUSTED_ID_TYPE = 'TRUSTED_ID_TYPE'
    TRUSTED_ID = 'TRUSTED_ID_NUMBER'
    ACCOUNT_NUMBER = 'ACCOUNT_NUMBER'
    ACCOUNT_DOMAIN = 'ACCOUNT_DOMAIN'
    DUNS_NUMBER = 'DUNS_NUMBER'
    NPI_NUMBER = 'NPI_NUMBER'
    LEI_NUMBER = 'LEI_NUMBER'

    WEBSITE = 'WEBSITE'
    EMAIL = 'EMAIL_ADDRESS'
    LINKEDIN = 'LINKEDIN'
    FACEBOOK = 'FACEBOOK'
    TWITTER = 'TWITTER'
    SKYPE = 'SKYPE'
    ZOOMROOM = 'ZOOMROOM'
    INSTAGRAM = 'INSTAGRAM'
    WHATSAPP = 'WHATSAPP'
    SIGNAL = 'SIGNAL'
    TELEGRAM = 'TELEGRAM'
    TANGO = 'TANGO'
    VIBER = 'VIBER'
    WECHAT = 'WECHAT'

    EMPLOYER = 'EMPLOYER_NAME'
    GROUP_ASSOCIATION_TYPE = 'GROUP_ASSOCIATION_TYPE'
    GROUP_ASSOCATION_ORG_NAME = 'GROUP_ASSOCIATION_ORG_NAME'
    GROUP_ASSN_ID_TYPE = 'GROUP_ASSN_ID_TYPE'
    GROUP_ASSN_ID = 'GROUP_ASSN_ID_NUMBER'

    NAME_TYPE = "NAME_TYPE"
    ADDR_TYPE = "ADDR_TYPE"
    PHONE_TYPE = "PHONE_TYPE"

    GENDER = "GENDER"
    DOB = "DATE_OF_BIRTH"
    DOD = "DATE_OF_DEATH"
    NATIONALITY = "NATIONALITY"
    CITIZENSHIP = "CITIZENSHIP"
    POB = "PLACE_OF_BIRTH"
    REGISTRATION_DATE = "REGISTRATION_DATE"
    REGISTRATION_COUNTRY = "REGISTRATION_COUNTRY"