ALTER TABLE OBS_ENT ADD COLUMN LOCK_DSRC_ACTION CHAR(1) ;
ALTER TABLE RES_ENT ADD COLUMN LOCK_DSRC_ACTION CHAR(1) ;
UPDATE SYS_VARS SET VAR_VALUE='1.15' WHERE VAR_GROUP='VERSION' AND VAR_CODE='SCHEMA' ;
