CREATE UNIQUE INDEX CFG_RCLASS_SK ON CFG_RCLASS(RCLASS_CODE) ;
CREATE UNIQUE INDEX CFG_RTYPE_SK ON CFG_RTYPE(RTYPE_CODE) ;
CREATE TABLE SYS_HW_CHECK (LIB_FEAT_ID BIGINT NOT NULL, FTYPE_ID smallint NOT NULL, FEAT_HASH CHAR(40) NOT NULL, FEAT_DESC VARCHAR(150), FELEM_VALUES VARCHAR(3000) NOT NULL, ANONYMIZED VARCHAR(5) NOT NULL, VERSION smallint NOT NULL, PRIMARY KEY(LIB_FEAT_ID)) ;
CREATE UNIQUE INDEX SYS_HW_CHECK_SK ON SYS_HW_CHECK(FEAT_HASH, FTYPE_ID, ANONYMIZED) ;
