ALTER TABLE SYS_CFG RENAME TO SYS_CFG_PRE_V110 ;
CREATE TABLE SYS_CFG (CONFIG_DATA_ID BIGINT NOT NULL, CONFIG_DATA CLOB NOT NULL, CONFIG_COMMENTS VARCHAR(200) NOT NULL, SYS_CREATE_DT TIMESTAMP NOT NULL, PRIMARY KEY(CONFIG_DATA_ID)) ;
CREATE TABLE SYS_VARS (VAR_GROUP VARCHAR(25) NOT NULL, VAR_CODE VARCHAR(25) NOT NULL, VAR_VALUE VARCHAR(25) NOT NULL, SYS_LSTUPD_DT TIMESTAMP, PRIMARY KEY(VAR_GROUP, VAR_CODE)) ;
INSERT INTO SYS_VARS (VAR_GROUP,VAR_CODE,VAR_VALUE) VALUES ('VERSION','SCHEMA','1.10');
